wmarket_db:
    restart: always
    image: mysql:latest
    volumes:
         - /var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=my-secret-pw
        - MYSQL_DATABASE=marketplace

wmarket:
    restart: always
    image: conwetlab/wmarket
    volumes:
        - /WMarket/static
    ports:
        - "80:8080"
    links:
        - wmarket_db
